name: Deploy to EC2

on:
  push:
    branches:
      - develop  # 푸시될 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Remove broken submodules
        run: |
          rm -rf .gitmodules .nvm
          git rm --cached .nvm demo-repository || true
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          
      - name: SSH to EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
          
            cd /home/ubuntu/demo-repository
            git pull origin develop
            
            if [ -d client ]; then
              cd client
            fi
          
            npm install
            npm run build
          
            if [ -d build ]; then
              sudo cp -r build/* /var/www/html/
            fi
            
            if [ -d ../server ]; then
              cd ../server
            elif [ -d server ]; then
              cd server
            else
              exit 1
            fi
          
            npm install
          
            if pm2 list | grep -q bookcard; then
              pm2 restart bookcard
            else
              pm2 start server.js --name bookcard
            fi
          
            pm2 save
            pm2 logs
          EOF
